import type {
  BundlePlacement,
  BundleTemplateInfo,
  CableTemplateInfo,
  BackboneEdgeInfo,
  DefaultBundlePlacementInfo,
  EditResult,
  GenerationTiming,
  GeometrySettings,
  LayoutSettings,
  ModelAssemblyBootstrapInput,
  OperationResult,
  PathPickInfo,
  PoleInfo,
  PoleTemplateInfo,
  PortInfo,
  ResolvedPathPointInfo,
  SpanInfo,
  SpanLayoutInfo,
  SupportNodeInfo,
  VisualPartInfo,
  VisualModelInstanceInfo,
  VisualSettings
} from "../model";
import type { RoadSegmentInput } from "../road";

// Generated by Emscripten before tests/build; it intentionally has no handwritten declaration file.
// @ts-expect-error generated module
import createWireModule from "../wasm-generated/wire_web_core.js";

export interface WireStateHandle {
  generate(
    points: Float64Array,
    bundleTemplateIds: number[],
    intervalM: number,
    poleTypeId: number,
    counts: number[],
    directionMode: number,
    maxTiltDeg: number,
    nodeSpecs?: Array<{ pointIndex: number; supportKind: number; nodeId: string }>
  ): EditResult;
  generatePlacements(
    points: Float64Array,
    bundlePlacements: BundlePlacement[],
    intervalM: number,
    poleTypeId: number,
    directionMode: number,
    maxTiltDeg: number,
    nodeSpecs?: Array<{ pointIndex: number; supportKind: number; nodeId: string }>
  ): EditResult;
  previewPlacements(
    points: Float64Array,
    bundlePlacements: BundlePlacement[],
    intervalM: number,
    poleTypeId: number,
    directionMode: number,
    maxTiltDeg: number,
    nodeSpecs?: Array<{ pointIndex: number; supportKind: number; nodeId: string }>
  ): EditResult & {
    parts: VisualPartInfo[];
    models: VisualModelInstanceInfo[];
    samples: Float64Array;
    poles: PoleInfo[];
  };
  resolveBranchPick(
    input: PathPickInfo,
    selectedBundleTemplateIds: number[]
  ): ResolvedPathPointInfo;
  previewResolveBranchPick(
    input: PathPickInfo,
    selectedBundleTemplateIds: number[]
  ): ResolvedPathPointInfo;
  clearPendingSupportNodes(): OperationResult;
  lastGenerationTiming(): GenerationTiming;
  visualScene(): {
    parts: VisualPartInfo[];
    models: VisualModelInstanceInfo[];
    samples: Float64Array;
  };
  configureModelAssemblies(input: ModelAssemblyBootstrapInput): OperationResult;
  poleCount(): number;
  pole(index: number): PoleInfo;
  portCount(): number;
  port(index: number): PortInfo;
  spanCount(): number;
  span(index: number): SpanInfo;
  spanLayout(spanId: string): SpanLayoutInfo;
  supportNodeCount(): number;
  supportNode(index: number): SupportNodeInfo;
  backboneEdgeCount(): number;
  backboneEdge(index: number): BackboneEdgeInfo;
  clearPoleOrientationOverride(poleId: string): OperationResult;
  clearSpanSocketOverride(spanId: string, isStartEndpoint: boolean): OperationResult;
  clearSpanBranchDownOverride(spanId: string): OperationResult;
  bundleTemplateCount(): number;
  bundleTemplate(index: number): BundleTemplateInfo;
  updateBundleTemplate(template: BundleTemplateInfo): OperationResult;
  resolveDefaultBundlePlacement(
    bundleTemplateId: number,
    poleTypeId: number,
    count: number
  ): DefaultBundlePlacementInfo;
  updateBackboneBundlePlacement(bundleId: string, placement: BundlePlacement): OperationResult;
  applyRelatedPoleType(bundleTemplateId: number): OperationResult;
  cableTemplateCount(): number;
  cableTemplate(index: number): CableTemplateInfo;
  updateCableTemplate(
    template: CableTemplateInfo,
    preferredSpanIds: string[]
  ): OperationResult;
  poleTemplateCount(): number;
  poleTemplate(index: number): PoleTemplateInfo;
  updatePoleTemplate(template: PoleTemplateInfo): OperationResult;
  geometrySettings(): GeometrySettings;
  updateGeometrySettings(settings: GeometrySettings): OperationResult;
  layoutSettings(): LayoutSettings;
  updateLayoutSettings(settings: LayoutSettings): OperationResult;
  visualSettings(): VisualSettings;
  updateVisualSettings(settings: VisualSettings): OperationResult;
  applyPoleTilt(poleIds: string[], maxTiltDeg: number): OperationResult;
  resetSpanReferenceLengths(): OperationResult;
  saveState(): string;
  loadState(text: string): OperationResult;
  loadStateWithModels(text: string, input: ModelAssemblyBootstrapInput): OperationResult;
  delete(): void;
}

export interface RoadMeshPayload {
  ownerSegmentId: number;
  material: string;
  vertices: number[];
  indices: number[];
}

export interface RoadSectionTemplatePayload {
  id: number;
  name: string;
  strips: Array<{
    id: number;
    function: "sidewalk" | "shoulder" | "carriageway" | "median";
    widthM: number;
  }>;
  sidewalkWidthM: number;
  laneWidthM: number;
  medianWidthM: number;
  laneCount: number;
  hasCenterLine: boolean;
  hasOuterLines: boolean;
  lanes: Array<{ id: number; direction: 0 | 1 }>;
  boundaries: Array<{ id: number; role: number }>;
}

export interface RoadLanePathPayload {
  segmentId: number;
  laneId: number;
  direction: 0 | 1;
  startSectionTemplateId: number;
  endSectionTemplateId: number;
  startSegmentDistanceM: number;
  endSegmentDistanceM: number;
  nodeAId: number;
  nodeBId: number;
  points: number[];
}

export interface RoadScenePayload {
  segmentCount: number;
  sectionTemplateCount: number;
  transitionCount: number;
  markingCount: number;
  connectionGateCount: number;
  junctionCount: number;
  corridorCount: number;
  nodes: RoadNodePayload[];
  centerlineSegments: RoadCenterlineSegmentPayload[];
  lanePaths: RoadLanePathPayload[];
  corridors: Array<{
    id: number;
    sectionTemplateId: number;
    lengthM: number;
    segments: Array<{ segmentId: number; reversed: boolean; lengthM: number }>;
  }>;
  sectionTemplates: RoadSectionTemplatePayload[];
  editableSegments: Array<{
    id: number;
    nodeAId: number;
    nodeBId: number;
    kind: "line" | "bezier";
    points: Array<{ x: number; y: number }>;
  }>;
  surfaceMeshes: RoadMeshPayload[];
  markingMeshes: RoadMeshPayload[];
  approaches: RoadApproachLayoutPayload[];
  junctions: RoadJunctionPayload[];
}

export interface RoadJunctionMarkingBoundaryPayload {
  boundaryId: number;
  role: number;
}

export interface RoadJunctionGatePayload {
  nodeId: number;
  segmentId: number;
  endpointRole: 0 | 1;
  markingBoundaries: RoadJunctionMarkingBoundaryPayload[];
}

export interface RoadJunctionMarkingOverridePayload {
  overrideId: number;
  action: number;
  sourceSegmentId: number;
  sourceBoundaryId: number;
  sourceRole: number;
  hasTarget: boolean;
  targetSegmentId?: number;
  targetBoundaryId?: number;
  targetRole?: number;
}

export interface RoadJunctionPayload {
  nodeId: number;
  gates: RoadJunctionGatePayload[];
  markingOverrides: RoadJunctionMarkingOverridePayload[];
}

export interface RoadMarkingEndpointInput {
  nodeId: number;
  segmentId: number;
  endpointRole: 0 | 1;
  boundaryId: number;
  role: number;
}

export interface RoadApproachLayoutPayload {
  nodeId: number;
  segmentId: number;
  endpointRole: 0 | 1;
  kind: number;
  autoSetbackM: number;
  resolvedSetbackM: number;
  manualSetback: boolean;
  manualSetbackM: number;
  autoLateralShiftM: number;
  resolvedLateralShiftM: number;
  manualLateralShift: boolean;
  manualLateralShiftM: number;
}

export interface RoadNodePayload {
  id: number;
  x: number;
  y: number;
  extensionCorridorId?: number;
}

export interface RoadCenterlineSegmentPayload {
  id: number;
  startX: number;
  startY: number;
  endX: number;
  endY: number;
  startSegmentDistanceM: number;
  endSegmentDistanceM: number;
}

export interface RoadSegmentResult extends OperationResult {
  segmentId?: number;
  corridorId?: number;
  endNodeId?: number;
}

export interface RoadIntervalPreview {
  startX: number;
  startY: number;
  handleAX: number;
  handleAY: number;
  handleBX: number;
  handleBY: number;
  endX: number;
  endY: number;
}

export interface RoadStateHandle {
  addSegment(input: RoadSegmentInput): RoadSegmentResult;
  previewSegment(input: RoadSegmentInput): OperationResult & { meshes: RoadMeshPayload[] };
  previewInterval(input: RoadSegmentInput): RoadIntervalPreview;
  addLane(input: RoadAddLaneInput): OperationResult & { laneId?: number };
  addConnectedLaneSegment(input: RoadConnectedLaneSegmentInput): OperationResult & { segmentId?: number };
  previewConnectedLaneSegment(input: RoadConnectedLaneSegmentInput): OperationResult & { meshes: RoadMeshPayload[] };
  scene(): RoadScenePayload;
  deleteSegment(segmentId: number): OperationResult;
  splitSegmentAtDistance(input: {
    segmentId: number;
    segmentDistanceM: number;
  }): OperationResult & { segmentId?: number };
  deleteSegmentRange(input: {
    segmentId: number;
    startSegmentDistanceM: number;
    endSegmentDistanceM: number;
  }): OperationResult;
  moveNode(input: { nodeId: number; x: number; y: number }): OperationResult;
  previewMoveNode(input: {
    nodeId: number;
    x: number;
    y: number;
  }): OperationResult & { meshes: RoadMeshPayload[] };
  editSegment(segmentId: number, input: RoadSegmentInput): OperationResult;
  previewEditSegment(segmentId: number, input: RoadSegmentInput): OperationResult & { meshes: RoadMeshPayload[] };
  updateSectionTemplate(input: Record<string, number | boolean>): OperationResult;
  addManualLine(input: Record<string, number | string>): OperationResult;
  addManualArea(input: Record<string, number | string>): OperationResult;
  undoSegment(): OperationResult;
  clear(): OperationResult;
  saveState(): string;
  loadState(text: string): OperationResult;
  delete(): void;
}

export interface RoadLaneEndpointInput {
  segmentId: number;
  laneId: number;
  endpointRole: 0 | 1;
}

export interface RoadBoundaryEndpointInput {
  segmentId: number;
  boundaryId: number;
  endpointRole: 0 | 1;
}

export interface RoadAddLaneInput {
  corridorId: number;
  direction: 0 | 1;
  side: "left" | "right";
  startSegmentId: number;
  startT: number;
  completeSegmentId: number;
  completeT: number;
  continuationEndNodeId: number;
  laneWidthM: number;
}

export interface RoadConnectedLaneSegmentInput extends RoadSegmentInput {
  sectionTemplateId: number;
  laneConnections: Array<{ source: RoadLaneEndpointInput; targetLaneId: number; kind: number }>;
  boundaryContinuations: Array<{ source: RoadBoundaryEndpointInput; targetBoundaryId: number; kind: number }>;
  sourceLaneConnections: Array<{ sourceLaneId: number; target: RoadLaneEndpointInput; kind: number }>;
  sourceBoundaryContinuations: Array<{ sourceBoundaryId: number; target: RoadBoundaryEndpointInput; kind: number }>;
}

export interface WireModule {
  WireState: new () => WireStateHandle;
  RoadState: new () => RoadStateHandle;
  wireBuildCommit(): string;
  wireBuildVersion(): string;
}

export interface WireModuleOptions {
  wasmBinary?: Uint8Array;
}

export async function loadWireModule(options?: WireModuleOptions): Promise<WireModule> {
  return createWireModule(options) as Promise<WireModule>;
}
